### ISSUE TITLE
Unnecessary code in the build

### ISSUE THREAD

**Issue by alandawi** [mediamonks/display-dev-server#10]
![weird_output](https://user-images.githubusercontent.com/1291730/154510821-7739952c-82b2-4b2e-bd0f-a537b80a93fe.png)

@mirkovw Is it necessary that this information is in the final file? (for example the path of the files with personal data)

**Comment by mirkovw** [comment]
@alandawi is this the generated JS chunk in the build folder? This is the config object, no? We reference this in our JS quite often so, yeah, I think its necessary. What would you propose?

**Comment by mirkovw** [comment]
Like, let's say you want to have some conditional code in your master JS based on the dimensions of the ad, you would need to have the width/height of the container available somewhere.

**Comment by alandawi** [comment]
@mirkovw Of course we need that information, but maybe there is some information that can be removed, such as no names/aliases appearing in the entry.html or entry.js.

**Comment by mirkovw** [comment]
Ahh, I understand now... Yes, that's a valid issue, agreed. I propose we fully remove the settings.entry object as it's not used during runtime.

**Comment by alandawi** [comment]
@mirkovw I did some quick tests with no success...

I tried to remove settings.entry, but at runtime they are needed to compile. Also 'fonts' are not inside settings, but it is also something that generates absolute paths...so the problem may be a bit more complicated since everything has an absolute path to compile.

**Comment by mirkovw** [comment]
Hey @alandawi yeah I did a quick check as well. The problem is a bit larger that we initially thought. ALL absolute paths need to be updated, so not just the settings.entry.html / js and fonts. Any path used for images / css files in the content object will also need to be updated.

I think that one way to do this would be to use a plugin for webpack that crawls through the richmediarc at the end of the webpack config, search for absolute paths (path.isAbsolute) and converts paths back to relative.

**Comment by mm-paulie** [comment]
I still some font files getting an absolute path so need to reset that as well.
